language: java

jdk:
  - oraclejdk7

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - curl https://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly
  - export CODACY_PROJECT_TOKEN=9612a19db312440d932a43d642355739
  - codacy-coverage-reporter -l Java -r coverage.xml
