language: java

jdk:
  - oraclejdk7

before_install:
  - curl http://www.jpm4j.org/install/script > jpmInstall.sh
  - sudo sh jpmInstall.sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - codacy-coverage-reporter -l Java -r target/site/cobertura/coverage.xml

