language: java

jdk:
  - oraclejdk7

before_install:
  - sudo curl https://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - codacy-coverage-reporter -l Java -r coverage.xml
